spring:
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:${TEST_MONGODB_BINDING_PORT}
      database: ${TEST_MONGODB_DATABASE}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${TEST_MARIADB_BINDING_PORT}/${TEST_MARIADB_DATABASE}
    username: ${TEST_MARIADB_ROOT_HOST}
    password: ${TEST_MARIADB_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

jwt:
  secret: ${JWT_SECRET_KEY}

openai:
  vision:
    api: ${OPEN_AI_VISION_API}
    token: ${OPEN_AI_VISION_TOKEN}
google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: ${GOOGLE_REDIRECT_URI}