spring:
  data:
    redis:
      host: k10a103.p.ssafy.io
      port: 6379
    mongodb:
      uri: mongodb://k10a103.p.ssafy.io:${MONGODB_BINDING_PORT}
      database: ${MONGODB_DATABASE}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

jwt:
  secret: ${JWT_SECRET_KEY}

openai:
  vision:
    api: ${OPEN_AI_VISION_API}
    token: ${OPEN_AI_VISION_TOKEN}
google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: ${GOOGLE_REDIRECT_URI}