spring:
  data:
    redis:
      host: k10a103.p.ssafy.io
      port: 6379
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@k10a103.p.ssafy.io:${MONGODB_BINDING_PORT}/?authSource=admin
      database: ${MONGODB_DATABASE}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET_KEY}

openai:
  vision:
    api: ${OPEN_AI_VISION_API}
    token: ${OPEN_AI_VISION_TOKEN}