spring:
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:${TEST_MONGODB_BINDING_PORT}
      database: ${TEST_MONGODB_DATABASE}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${TEST_MARIADB_BINDING_PORT}/${TEST_MARIADB_DATABASE}
    username: ${TEST_MARIADB_ROOT_HOST}
    password: ${TEST_MARIADB_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/user.gender.read
              - https://www.googleapis.com/auth/user.birthday.read
              - https://www.googleapis.com/auth/fitness.body.read
              - https://www.googleapis.com/auth/fitness.heart_rate.read
              - https://www.googleapis.com/auth/fitness.location.read
              - https://www.googleapis.com/auth/fitness.sleep.read
              - https://www.googleapis.com/auth/fitness.activity.read
              - https://www.googleapis.com/auth/fitness.activity.write


jwt:
  secret: ${JWT_SECRET_KEY}

openai:
  vision:
    api: ${OPEN_AI_VISION_API}
    token: ${OPEN_AI_VISION_TOKEN}