spring:
  data:
    redis:
      host: k10a103.p.ssafy.io
      port: 6378
    mongodb:
      url: ${SPRING_DATA_MONGODB_URL}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET_KEY}
